#!/usr/bin/env bash

# ~/.macos — https://mths.be/macos
# Modified by Juansereina
# Run without downloading:

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# Juansereina's Customizations                                                       #
###############################################################################

echo "Hello $(whoami)! Let's get you set up."

echo "installing homebrew"
# install homebrew https://brew.sh
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "brew installing stuff"
# git version control
# zsh tooling
# gnupg GPG
brew install git zsh gnupg

echo "switch the default shell used in your terminal"
sudo chsh -s /bin/zsh

echo "installing nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash

echo "installing Visual Studio Code"
brew cask install visual-studio-code firefox

echo "installing Fira Code font"
brew tap homebrew/cask-fonts
brew cask install font-fira-code

echo "installing antigen"
curl -L git.io/antigen > antigen.zsh

echo "installing colorls"
gem install colorls

echo "Generating an RSA token for GitHub"
mkdir -p ~/.ssh
touch ~/.ssh/config
ssh-keygen -t rsa -b 4096 -C "juansereina@outlook.com"
echo "Host *\n AddKeysToAgent yes\n UseKeychain yes\n IdentityFile ~/.ssh/id_rsa" | tee ~/.ssh/config
eval "$(ssh-agent -s)"
echo "run 'pbcopy < ~/.ssh/id_rsa.pub' and paste that into GitHub"
echo "run 'ssh-add -K ~/.ssh/id_rsa' to add your SSH private key to the ssh-agent and store your passphrase in the keychain"
